'use client'

import { useState, useEffect, useCallback, useMemo } from 'react'
import { toast } from 'sonner'
import {
  BookOpen,
  Search,
  RefreshCw,
  Loader2,
  Sparkles,
  ChevronDown,
  ChevronRight,
  Database,
  RotateCcw,
  MessageSquare,
  GitCommit,
  Filter,
  ArrowUpDown,
  CheckCircle2,
  AlertCircle,
  Clock,
} from 'lucide-react'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Separator } from '@/components/ui/separator'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from '@/components/ui/collapsible'
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip'
import type { CatalogTable, CatalogColumn, SupabaseConnection } from '@/lib/supabase-types'
import { formatDistanceToNow } from 'date-fns'

const DEMO_CATALOG_TABLES: CatalogTable[] = [
  {
    id: 'demo-1', schema_name: 'public', table_name: 'users', row_count: 10241,
    ai_description: 'Core user accounts table. Stores authentication identities, profile metadata, and subscription tier. Referenced by nearly every other table in the schema.',
    profiled_at: '2024-06-15T09:12:00Z', created_at: '2024-01-15T00:00:00Z',
    columns: [
      { id: 'c1-1', table_id: 'demo-1', column_name: 'id', data_type: 'uuid', nullable: false, null_pct: 0, distinct_count: 10241, sample_values: ['a1b2c3d4-...', 'e5f6a7b8-...'], min_val: null, max_val: null, ai_description: 'Primary key. UUID v4 generated by Supabase Auth.' },
      { id: 'c1-2', table_id: 'demo-1', column_name: 'email', data_type: 'text', nullable: false, null_pct: 0, distinct_count: 10241, sample_values: ['alice@example.com', 'bob@corp.io'], min_val: null, max_val: null, ai_description: 'Unique email address used for authentication and notifications.' },
      { id: 'c1-3', table_id: 'demo-1', column_name: 'username', data_type: 'text', nullable: false, null_pct: 0, distinct_count: 10198, sample_values: ['alice_dev', 'bob42', 'carol_writes'], min_val: null, max_val: null, ai_description: 'Public-facing display name. Unique and immutable after 30 days.' },
      { id: 'c1-4', table_id: 'demo-1', column_name: 'plan', data_type: 'text', nullable: false, null_pct: 0, distinct_count: 3, sample_values: ['free', 'pro', 'enterprise'], min_val: null, max_val: null, ai_description: 'Subscription tier. Determines feature access and rate limits.' },
      { id: 'c1-5', table_id: 'demo-1', column_name: 'created_at', data_type: 'timestamptz', nullable: false, null_pct: 0, distinct_count: 10241, sample_values: ['2024-01-15', '2024-03-22'], min_val: '2024-01-15', max_val: '2024-06-14', ai_description: 'Account creation timestamp.' },
      { id: 'c1-6', table_id: 'demo-1', column_name: 'avatar_url', data_type: 'text', nullable: true, null_pct: 31.2, distinct_count: 7043, sample_values: ['https://...', null], min_val: null, max_val: null, ai_description: 'CDN URL for profile avatar. Null for users who have not uploaded a photo.' },
    ],
  },
  {
    id: 'demo-2', schema_name: 'public', table_name: 'posts', row_count: 52847,
    ai_description: 'User-generated content (blog posts, articles). Supports draft/published workflow with soft-delete via deleted_at. Full-text search index on title + body.',
    profiled_at: '2024-06-15T09:13:00Z', created_at: '2024-01-15T00:00:00Z',
    columns: [
      { id: 'c2-1', table_id: 'demo-2', column_name: 'id', data_type: 'uuid', nullable: false, null_pct: 0, distinct_count: 52847, sample_values: [], min_val: null, max_val: null, ai_description: 'Primary key.' },
      { id: 'c2-2', table_id: 'demo-2', column_name: 'user_id', data_type: 'uuid', nullable: false, null_pct: 0, distinct_count: 8134, sample_values: [], min_val: null, max_val: null, ai_description: 'Author FK → users.id. ~79% of users have at least one post.' },
      { id: 'c2-3', table_id: 'demo-2', column_name: 'title', data_type: 'text', nullable: false, null_pct: 0, distinct_count: 52831, sample_values: ['Getting started with Next.js', 'My first post'], min_val: null, max_val: null, ai_description: 'Post headline. Max 255 characters enforced by a check constraint.' },
      { id: 'c2-4', table_id: 'demo-2', column_name: 'status', data_type: 'text', nullable: false, null_pct: 0, distinct_count: 3, sample_values: ['draft', 'published', 'archived'], min_val: null, max_val: null, ai_description: 'Publication state. Only "published" posts are visible to non-authors.' },
      { id: 'c2-5', table_id: 'demo-2', column_name: 'view_count', data_type: 'integer', nullable: false, null_pct: 0, distinct_count: 4812, sample_values: ['0', '42', '1893'], min_val: '0', max_val: '284931', ai_description: 'Lifetime view counter. Incremented by the view-tracking edge function.' },
      { id: 'c2-6', table_id: 'demo-2', column_name: 'deleted_at', data_type: 'timestamptz', nullable: true, null_pct: 97.1, distinct_count: 1531, sample_values: [null], min_val: null, max_val: null, ai_description: 'Soft-delete timestamp. Non-null means the post has been removed.' },
    ],
  },
  {
    id: 'demo-3', schema_name: 'public', table_name: 'comments', row_count: 198432,
    ai_description: 'Threaded comments on posts. Supports one level of nesting via parent_id self-reference. Moderation status tracked on each row.',
    profiled_at: '2024-06-15T09:14:00Z', created_at: '2024-01-15T00:00:00Z',
    columns: [
      { id: 'c3-1', table_id: 'demo-3', column_name: 'id', data_type: 'uuid', nullable: false, null_pct: 0, distinct_count: 198432, sample_values: [], min_val: null, max_val: null, ai_description: 'Primary key.' },
      { id: 'c3-2', table_id: 'demo-3', column_name: 'post_id', data_type: 'uuid', nullable: false, null_pct: 0, distinct_count: 41207, sample_values: [], min_val: null, max_val: null, ai_description: 'Parent post FK → posts.id.' },
      { id: 'c3-3', table_id: 'demo-3', column_name: 'user_id', data_type: 'uuid', nullable: false, null_pct: 0, distinct_count: 9821, sample_values: [], min_val: null, max_val: null, ai_description: 'Commenter FK → users.id.' },
      { id: 'c3-4', table_id: 'demo-3', column_name: 'parent_id', data_type: 'uuid', nullable: true, null_pct: 68.3, distinct_count: 63241, sample_values: [null], min_val: null, max_val: null, ai_description: 'Self-reference for replies. Null = top-level comment.' },
      { id: 'c3-5', table_id: 'demo-3', column_name: 'body', data_type: 'text', nullable: false, null_pct: 0, distinct_count: 197891, sample_values: ['Great article!', 'This helped a lot.'], min_val: null, max_val: null, ai_description: 'Comment text. Markdown supported, sanitized on read.' },
      { id: 'c3-6', table_id: 'demo-3', column_name: 'is_flagged', data_type: 'boolean', nullable: false, null_pct: 0, distinct_count: 2, sample_values: ['false', 'true'], min_val: null, max_val: null, ai_description: 'Moderation flag. Flagged comments are hidden pending review.' },
    ],
  },
  {
    id: 'demo-4', schema_name: 'public', table_name: 'likes', row_count: 445213,
    ai_description: 'Post and comment reactions. Composite unique constraint on (user_id, target_type, target_id) prevents duplicate likes.',
    profiled_at: '2024-06-15T09:14:30Z', created_at: '2024-01-15T00:00:00Z',
    columns: [
      { id: 'c4-1', table_id: 'demo-4', column_name: 'id', data_type: 'bigint', nullable: false, null_pct: 0, distinct_count: 445213, sample_values: ['1', '2', '3'], min_val: '1', max_val: '445213', ai_description: 'Auto-increment primary key.' },
      { id: 'c4-2', table_id: 'demo-4', column_name: 'user_id', data_type: 'uuid', nullable: false, null_pct: 0, distinct_count: 10241, sample_values: [], min_val: null, max_val: null, ai_description: 'Who liked it → users.id.' },
      { id: 'c4-3', table_id: 'demo-4', column_name: 'target_type', data_type: 'text', nullable: false, null_pct: 0, distinct_count: 2, sample_values: ['post', 'comment'], min_val: null, max_val: null, ai_description: 'Polymorphic type discriminator.' },
      { id: 'c4-4', table_id: 'demo-4', column_name: 'target_id', data_type: 'uuid', nullable: false, null_pct: 0, distinct_count: 198432, sample_values: [], min_val: null, max_val: null, ai_description: 'Polymorphic FK — points to posts.id or comments.id depending on target_type.' },
    ],
  },
  {
    id: 'demo-5', schema_name: 'public', table_name: 'categories', row_count: 42,
    ai_description: 'Content taxonomy. Static reference table — new categories require a migration. Supports hierarchical nesting via parent_id.',
    profiled_at: '2024-06-15T09:15:00Z', created_at: '2024-01-15T00:00:00Z',
    columns: [
      { id: 'c5-1', table_id: 'demo-5', column_name: 'id', data_type: 'integer', nullable: false, null_pct: 0, distinct_count: 42, sample_values: ['1', '2', '3'], min_val: '1', max_val: '42', ai_description: 'Sequential primary key.' },
      { id: 'c5-2', table_id: 'demo-5', column_name: 'name', data_type: 'text', nullable: false, null_pct: 0, distinct_count: 42, sample_values: ['Technology', 'Design', 'Business'], min_val: null, max_val: null, ai_description: 'Human-readable category label. Unique.' },
      { id: 'c5-3', table_id: 'demo-5', column_name: 'slug', data_type: 'text', nullable: false, null_pct: 0, distinct_count: 42, sample_values: ['technology', 'design', 'business'], min_val: null, max_val: null, ai_description: 'URL-safe slug for routing. Lowercase, hyphen-separated.' },
      { id: 'c5-4', table_id: 'demo-5', column_name: 'parent_id', data_type: 'integer', nullable: true, null_pct: 57.1, distinct_count: 18, sample_values: [null, '1', '3'], min_val: null, max_val: null, ai_description: 'Parent category for subcategory nesting. Null = top-level category.' },
    ],
  },
  {
    id: 'demo-6', schema_name: 'public', table_name: 'post_categories', row_count: 87291,
    ai_description: 'Many-to-many join table linking posts to categories. Composite PK on (post_id, category_id). A post can belong to up to 5 categories (enforced by trigger).',
    profiled_at: '2024-06-15T09:15:30Z', created_at: '2024-01-15T00:00:00Z',
    columns: [
      { id: 'c6-1', table_id: 'demo-6', column_name: 'post_id', data_type: 'uuid', nullable: false, null_pct: 0, distinct_count: 52847, sample_values: [], min_val: null, max_val: null, ai_description: 'FK → posts.id.' },
      { id: 'c6-2', table_id: 'demo-6', column_name: 'category_id', data_type: 'integer', nullable: false, null_pct: 0, distinct_count: 42, sample_values: ['1', '7', '14'], min_val: '1', max_val: '42', ai_description: 'FK → categories.id.' },
    ],
  },
  {
    id: 'demo-7', schema_name: 'public', table_name: 'audit_logs', row_count: 3891042,
    ai_description: 'Append-only audit trail for all data mutations. Written by a set of database triggers. Partitioned by month. Do not query without a time-range filter — full scans are expensive.',
    profiled_at: '2024-06-15T09:16:00Z', created_at: '2024-01-15T00:00:00Z',
    columns: [
      { id: 'c7-1', table_id: 'demo-7', column_name: 'id', data_type: 'bigint', nullable: false, null_pct: 0, distinct_count: 3891042, sample_values: [], min_val: '1', max_val: '3891042', ai_description: 'Sequential ID within partition.' },
      { id: 'c7-2', table_id: 'demo-7', column_name: 'table_name', data_type: 'text', nullable: false, null_pct: 0, distinct_count: 7, sample_values: ['users', 'posts', 'comments'], min_val: null, max_val: null, ai_description: 'Name of the table that was mutated.' },
      { id: 'c7-3', table_id: 'demo-7', column_name: 'operation', data_type: 'text', nullable: false, null_pct: 0, distinct_count: 3, sample_values: ['INSERT', 'UPDATE', 'DELETE'], min_val: null, max_val: null, ai_description: 'DML operation type.' },
      { id: 'c7-4', table_id: 'demo-7', column_name: 'old_data', data_type: 'jsonb', nullable: true, null_pct: 41.2, distinct_count: null, sample_values: [null, '{"status":"draft"}'], min_val: null, max_val: null, ai_description: 'Row state before the change. Null for INSERT operations.' },
      { id: 'c7-5', table_id: 'demo-7', column_name: 'new_data', data_type: 'jsonb', nullable: true, null_pct: 8.7, distinct_count: null, sample_values: ['{"status":"published"}', null], min_val: null, max_val: null, ai_description: 'Row state after the change. Null for DELETE operations.' },
      { id: 'c7-6', table_id: 'demo-7', column_name: 'created_at', data_type: 'timestamptz', nullable: false, null_pct: 0, distinct_count: 3891042, sample_values: [], min_val: '2024-01-15', max_val: '2024-06-15', ai_description: 'Timestamp of the mutation. Partition key.' },
    ],
  },
  {
    id: 'demo-8', schema_name: 'public', table_name: 'notifications', row_count: 124876,
    ai_description: 'In-app notification queue. Consumed by the notification-dispatcher edge function. Read receipts tracked via read_at.',
    profiled_at: '2024-06-15T09:16:30Z', created_at: '2024-01-15T00:00:00Z',
    columns: [
      { id: 'c8-1', table_id: 'demo-8', column_name: 'id', data_type: 'uuid', nullable: false, null_pct: 0, distinct_count: 124876, sample_values: [], min_val: null, max_val: null, ai_description: 'Primary key.' },
      { id: 'c8-2', table_id: 'demo-8', column_name: 'user_id', data_type: 'uuid', nullable: false, null_pct: 0, distinct_count: 9847, sample_values: [], min_val: null, max_val: null, ai_description: 'Recipient FK → users.id.' },
      { id: 'c8-3', table_id: 'demo-8', column_name: 'type', data_type: 'text', nullable: false, null_pct: 0, distinct_count: 6, sample_values: ['new_comment', 'new_like', 'mention', 'follow'], min_val: null, max_val: null, ai_description: 'Event type. Determines notification message template and routing.' },
      { id: 'c8-4', table_id: 'demo-8', column_name: 'payload', data_type: 'jsonb', nullable: false, null_pct: 0, distinct_count: null, sample_values: ['{"post_id":"...","actor":"alice"}'], min_val: null, max_val: null, ai_description: 'Event-specific payload. Schema varies by type.' },
      { id: 'c8-5', table_id: 'demo-8', column_name: 'read_at', data_type: 'timestamptz', nullable: true, null_pct: 62.4, distinct_count: 47123, sample_values: [null, '2024-06-10T14:22:00Z'], min_val: null, max_val: null, ai_description: 'When the user opened the notification. Null = unread.' },
    ],
  },
]

type SortKey = 'name' | 'row_count' | 'profiled_at'

function ProfileStatBadge({ label, value }: { label: string; value: string | number | null }) {
  if (value === null || value === undefined) return null
  return (
    <span className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded text-[10px] font-mono bg-muted text-muted-foreground">
      <span className="text-foreground/50">{label}</span>
      <span>{String(value)}</span>
    </span>
  )
}

function ColumnRow({ col }: { col: CatalogColumn }) {
  const samples = Array.isArray(col.sample_values) ? col.sample_values.slice(0, 5) : []
  const nullPct = col.null_pct !== null ? `${Number(col.null_pct).toFixed(1)}%` : null

  return (
    <div className="grid grid-cols-[160px_1fr] gap-3 px-3 py-2 border-b border-border/40 last:border-0">
      <div className="flex flex-col gap-0.5 min-w-0">
        <span className="font-mono text-xs font-medium truncate">{col.column_name}</span>
        <div className="flex flex-wrap gap-1 mt-0.5">
          <Badge variant="outline" className="text-[10px] px-1 py-0 h-4 font-mono">
            {col.data_type || 'unknown'}
          </Badge>
          {col.nullable === false && (
            <Badge variant="secondary" className="text-[10px] px-1 py-0 h-4">NOT NULL</Badge>
          )}
        </div>
      </div>
      <div className="flex flex-col gap-1 min-w-0">
        {col.ai_description ? (
          <p className="text-xs text-foreground leading-relaxed">{col.ai_description}</p>
        ) : (
          <p className="text-xs text-muted-foreground italic">No AI description yet</p>
        )}
        <div className="flex flex-wrap gap-1">
          {nullPct !== null && <ProfileStatBadge label="null" value={nullPct} />}
          {col.distinct_count !== null && (
            <ProfileStatBadge label="distinct" value={col.distinct_count.toLocaleString()} />
          )}
          {col.min_val && <ProfileStatBadge label="min" value={col.min_val} />}
          {col.max_val && <ProfileStatBadge label="max" value={col.max_val} />}
          {samples.length > 0 && (
            <span className="inline-flex items-center gap-1 text-[10px] text-muted-foreground">
              samples:
              {samples.map((s, i) => (
                <span key={i} className="px-1 py-0.5 rounded bg-muted font-mono text-foreground/70">
                  {String(s)}
                </span>
              ))}
            </span>
          )}
        </div>
      </div>
    </div>
  )
}

interface TableCardProps {
  table: CatalogTable
  onReProfile: (tableName: string) => void
  onGenerateAI: (table: CatalogTable) => void
  onCommit: (table: CatalogTable) => void
  isReprofiling: boolean
  isGenerating: boolean
  isCommitting: boolean
}

function TableCard({ table, onReProfile, onGenerateAI, onCommit, isReprofiling, isGenerating, isCommitting }: TableCardProps) {
  const [open, setOpen] = useState(false)
  const cols = table.columns || []
  const profiledAgo = table.profiled_at
    ? formatDistanceToNow(new Date(table.profiled_at), { addSuffix: true })
    : null

  return (
    <div className="border rounded-md bg-card group">
      {/* Header row */}
      <div className="flex items-center gap-3 px-3 py-2.5 hover:bg-muted/30 transition-colors">
        {/* Expand toggle */}
        <button
          onClick={() => cols.length > 0 && setOpen(!open)}
          className="text-muted-foreground hover:text-foreground transition-colors shrink-0"
          disabled={cols.length === 0}
        >
          {open ? <ChevronDown className="size-3.5" /> : <ChevronRight className="size-3.5" />}
        </button>

        {/* Table name */}
        <div className="flex items-center gap-2 min-w-0 flex-1">
          <Badge variant="outline" className="text-[10px] font-mono px-1 py-0 h-4 shrink-0 hidden sm:inline-flex">
            {table.schema_name}
          </Badge>
          <span className="font-mono text-xs font-semibold truncate">{table.table_name}</span>
        </div>

        {/* Meta */}
        <div className="flex items-center gap-3 text-[11px] text-muted-foreground shrink-0">
          {table.row_count !== null && (
            <span className="tabular-nums hidden sm:block">{table.row_count.toLocaleString()} rows</span>
          )}
          {profiledAgo && (
            <span className="hidden lg:block">{profiledAgo}</span>
          )}
          {cols.length > 0 && (
            <span className="hidden sm:block">{cols.length} cols</span>
          )}
        </div>

        {/* Actions */}
        <TooltipProvider>
          <div className="flex items-center gap-0.5 opacity-0 group-hover:opacity-100 transition-opacity shrink-0">
            <Tooltip>
              <TooltipTrigger asChild>
                <Button variant="ghost" size="sm" onClick={() => onReProfile(table.table_name)} disabled={isReprofiling} className="h-6 w-6 p-0">
                  {isReprofiling ? <Loader2 className="size-3 animate-spin" /> : <RotateCcw className="size-3" />}
                </Button>
              </TooltipTrigger>
              <TooltipContent>Re-profile</TooltipContent>
            </Tooltip>
            <Tooltip>
              <TooltipTrigger asChild>
                <Button variant="ghost" size="sm" onClick={() => onGenerateAI(table)} disabled={isGenerating || !table.profiled_at} className="h-6 w-6 p-0">
                  {isGenerating ? <Loader2 className="size-3 animate-spin" /> : <Sparkles className="size-3" />}
                </Button>
              </TooltipTrigger>
              <TooltipContent>{table.profiled_at ? 'Generate AI' : 'Profile first'}</TooltipContent>
            </Tooltip>
            <Tooltip>
              <TooltipTrigger asChild>
                <Button variant="ghost" size="sm" onClick={() => onCommit(table)} disabled={isCommitting || !table.ai_description} className="h-6 w-6 p-0">
                  {isCommitting ? <Loader2 className="size-3 animate-spin" /> : <GitCommit className="size-3" />}
                </Button>
              </TooltipTrigger>
              <TooltipContent>{table.ai_description ? 'Commit to schema' : 'Generate AI first'}</TooltipContent>
            </Tooltip>
          </div>
        </TooltipProvider>
      </div>

      {/* AI description — shown below header when present */}
      {table.ai_description && (
        <div className="px-3 pb-2.5 -mt-1">
          <p className="text-xs text-muted-foreground leading-relaxed">{table.ai_description}</p>
        </div>
      )}

      {/* Column details — expandable */}
      {open && cols.length > 0 && (
        <div className="border-t">
          {cols.map((col) => (
            <ColumnRow key={col.id} col={col} />
          ))}
        </div>
      )}
    </div>
  )
}

export function DataCatalogPanel({
  connection: activeConnection,
  isDemoMode = false,
}: {
  connection: SupabaseConnection | null
  isDemoMode?: boolean
}) {
  const [schemaReady, setSchemaReady] = useState<boolean | null>(null)
  const [tables, setTables] = useState<CatalogTable[]>([])
  const [isLoading, setIsLoading] = useState(false)
  const [isSettingUp, setIsSettingUp] = useState(false)
  const [isProfilingAll, setIsProfilingAll] = useState(false)
  const [isGeneratingAll, setIsGeneratingAll] = useState(false)
  const [reprofilingTable, setReprofilingTable] = useState<string | null>(null)
  const [generatingTable, setGeneratingTable] = useState<string | null>(null)
  const [committingTable, setCommittingTable] = useState<string | null>(null)

  const [search, setSearch] = useState('')
  const [schemaFilter, setSchemaFilter] = useState('all')
  const [sortKey, setSortKey] = useState<SortKey>('name')

  const loadCatalog = useCallback(async () => {
    if (!activeConnection) return
    setIsLoading(true)
    try {
      const res = await fetch('/api/catalog/load', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ connection: activeConnection }),
      })
      const data = await res.json()
      if (data.error) {
        toast.error('Failed to load catalog', { description: data.error })
        setSchemaReady(false)
      } else {
        setSchemaReady(data.schemaReady)
        setTables(data.tables || [])
      }
    } catch {
      toast.error('Failed to load catalog')
      setSchemaReady(false)
    } finally {
      setIsLoading(false)
    }
  }, [activeConnection])

  useEffect(() => {
    if (isDemoMode) {
      setTables(DEMO_CATALOG_TABLES)
      setSchemaReady(true)
      return
    }
    if (activeConnection) loadCatalog()
  }, [activeConnection, loadCatalog, isDemoMode])

  const handleSetup = async () => {
    if (!activeConnection) return
    setIsSettingUp(true)
    try {
      const res = await fetch('/api/catalog/setup', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ connection: activeConnection }),
      })
      const data = await res.json()
      if (data.error) {
        toast.error('Setup failed', { description: data.error })
      } else {
        toast.success('Catalog schema created')
        await loadCatalog()
      }
    } catch {
      toast.error('Setup failed')
    } finally {
      setIsSettingUp(false)
    }
  }

  const handleProfileAll = async () => {
    if (!activeConnection) return
    setIsProfilingAll(true)
    try {
      const res = await fetch('/api/catalog/profile', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ connection: activeConnection }),
      })
      const data = await res.json()
      if (data.error) {
        toast.error('Profiling failed', { description: data.error })
      } else {
        toast.success(`Profiled ${data.profiled} tables`)
        await loadCatalog()
      }
    } catch {
      toast.error('Profiling failed')
    } finally {
      setIsProfilingAll(false)
    }
  }

  const handleReProfile = async (tableName: string) => {
    if (!activeConnection) return
    setReprofilingTable(tableName)
    try {
      const res = await fetch('/api/catalog/profile', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ connection: activeConnection, tableNames: [tableName] }),
      })
      const data = await res.json()
      if (data.error) {
        toast.error('Re-profile failed', { description: data.error })
      } else {
        toast.success(`Re-profiled ${tableName}`)
        await loadCatalog()
      }
    } catch {
      toast.error('Re-profile failed')
    } finally {
      setReprofilingTable(null)
    }
  }

  const invokeAIGeneration = async (table: CatalogTable) => {
    if (!activeConnection) return
    const cols = table.columns || []

    const columnPayload = cols.map((c) => ({
      name: c.column_name,
      type: c.data_type || 'unknown',
      nullable: c.nullable ?? true,
      nullPct: c.null_pct ?? 0,
      distinctCount: c.distinct_count,
      sampleValues: Array.isArray(c.sample_values) ? c.sample_values : [],
    }))

    const res = await fetch('/api/edge-functions/invoke', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        connection: activeConnection,
        functionName: 'catalog-generator',
        method: 'POST',
        body: {
          tableName: table.table_name,
          schemaName: table.schema_name,
          rowCount: table.row_count ?? 0,
          columns: columnPayload,
        },
      }),
    })
    const result = await res.json()

    if (result.error) {
      throw new Error(result.error)
    }

    const aiData = result.data as {
      tableDescription?: string
      columnDescriptions?: Record<string, string>
      error?: string
    }

    if (aiData.error) throw new Error(aiData.error)

    const managementToken = activeConnection.accessToken ||
      (activeConnection.serviceRoleKey?.startsWith('sbp_') ? activeConnection.serviceRoleKey : null)
    if (!managementToken) throw new Error('Management API token required')

    // Save table description
    if (aiData.tableDescription) {
      const safe = aiData.tableDescription.replace(/'/g, "''")
      await fetch('/api/sql', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          connection: activeConnection,
          query: `UPDATE catalog_tables SET ai_description = '${safe}' WHERE id = '${table.id}';`,
        }),
      })
    }

    // Save column descriptions
    if (aiData.columnDescriptions) {
      for (const [colName, desc] of Object.entries(aiData.columnDescriptions)) {
        const safeDesc = (desc as string).replace(/'/g, "''")
        const safeCol = colName.replace(/'/g, "''")
        await fetch('/api/sql', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            connection: activeConnection,
            query: `UPDATE catalog_columns SET ai_description = '${safeDesc}' WHERE table_id = '${table.id}' AND column_name = '${safeCol}';`,
          }),
        })
      }
    }

    return aiData
  }

  const handleGenerateAI = async (table: CatalogTable) => {
    setGeneratingTable(table.table_name)
    try {
      await invokeAIGeneration(table)
      toast.success(`AI descriptions generated for ${table.table_name}`)
      await loadCatalog()
    } catch (err) {
      toast.error('AI generation failed', {
        description: err instanceof Error ? err.message : 'Unknown error',
      })
    } finally {
      setGeneratingTable(null)
    }
  }

  const handleGenerateAll = async () => {
    const unprofiled = tables.filter((t) => !t.profiled_at)
    if (unprofiled.length === tables.length) {
      toast.error('Profile tables first before generating AI descriptions')
      return
    }
    setIsGeneratingAll(true)
    let success = 0
    let failed = 0
    for (const table of tables.filter((t) => t.profiled_at)) {
      try {
        await invokeAIGeneration(table)
        success++
      } catch {
        failed++
      }
    }
    toast.success(`AI generation complete: ${success} succeeded${failed > 0 ? `, ${failed} failed` : ''}`)
    await loadCatalog()
    setIsGeneratingAll(false)
  }

  const handleCommit = async (table: CatalogTable) => {
    if (!activeConnection) return
    setCommittingTable(table.table_name)
    try {
      const res = await fetch('/api/catalog/commit', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          connection: activeConnection,
          tableId: table.id,
          schemaName: table.schema_name,
          tableName: table.table_name,
        }),
      })
      const data = await res.json()
      if (data.error) {
        toast.error('Commit failed', { description: data.error })
      } else if (data.committed === 0) {
        toast.info(data.message || 'Nothing to commit')
      } else {
        toast.success(`Committed ${data.committed} comment(s) to schema`, {
          description: `COMMENT ON TABLE/COLUMN written for ${table.table_name}`,
        })
      }
    } catch {
      toast.error('Commit failed')
    } finally {
      setCommittingTable(null)
    }
  }

  const schemas = useMemo(() => {
    const s = new Set(tables.map((t) => t.schema_name))
    return Array.from(s).sort()
  }, [tables])

  const filteredTables = useMemo(() => {
    let result = tables

    if (schemaFilter !== 'all') {
      result = result.filter((t) => t.schema_name === schemaFilter)
    }

    if (search.trim()) {
      const q = search.toLowerCase()
      result = result.filter(
        (t) =>
          t.table_name.toLowerCase().includes(q) ||
          t.schema_name.toLowerCase().includes(q) ||
          t.ai_description?.toLowerCase().includes(q) ||
          t.columns?.some(
            (c) =>
              c.column_name.toLowerCase().includes(q) ||
              c.ai_description?.toLowerCase().includes(q)
          )
      )
    }

    result = [...result].sort((a, b) => {
      if (sortKey === 'name') return a.table_name.localeCompare(b.table_name)
      if (sortKey === 'row_count') return (b.row_count ?? 0) - (a.row_count ?? 0)
      if (sortKey === 'profiled_at') {
        if (!a.profiled_at) return 1
        if (!b.profiled_at) return -1
        return new Date(b.profiled_at).getTime() - new Date(a.profiled_at).getTime()
      }
      return 0
    })

    return result
  }, [tables, schemaFilter, search, sortKey])

  const profiledCount = tables.filter((t) => t.profiled_at).length
  const aiCount = tables.filter((t) => t.ai_description).length

  // — No connection —
  if (!activeConnection) {
    return (
      <Card className="mt-6">
        <CardContent className="py-16 flex flex-col items-center justify-center text-center gap-3">
          <BookOpen className="size-10 text-muted-foreground/40" />
          <p className="text-lg font-medium">No connection selected</p>
          <p className="text-sm text-muted-foreground">Connect to a Supabase project to use the Data Catalog.</p>
        </CardContent>
      </Card>
    )
  }

  // — Loading —
  if (isLoading && schemaReady === null) {
    return (
      <div className="flex items-center justify-center py-20 text-muted-foreground">
        <Loader2 className="size-5 animate-spin mr-2" />
        Loading catalog...
      </div>
    )
  }

  // — Setup required —
  if (schemaReady === false) {
    return (
      <div className="mt-6 max-w-lg mx-auto">
        <Card>
          <CardHeader>
            <div className="flex items-center gap-3 mb-1">
              <div className="p-2 rounded-lg bg-primary/10">
                <BookOpen className="size-5 text-primary" />
              </div>
              <div>
                <CardTitle>Data Catalog</CardTitle>
                <CardDescription>Initialize schema to get started</CardDescription>
              </div>
            </div>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-sm text-muted-foreground">
              The catalog requires two tables in your Supabase project: <code className="font-mono text-xs bg-muted px-1 py-0.5 rounded">catalog_tables</code> and{' '}
              <code className="font-mono text-xs bg-muted px-1 py-0.5 rounded">catalog_columns</code>.
              Click below to create them. A Management API token is required.
            </p>
            <div className="rounded-md border border-amber-200 dark:border-amber-800 bg-amber-50 dark:bg-amber-950/30 px-3 py-2.5 text-xs text-amber-800 dark:text-amber-300">
              Also deploy the <code className="font-mono">catalog-generator</code> edge function and set{' '}
              <code className="font-mono">OPENAI_API_KEY</code> as a Supabase secret for AI descriptions.
            </div>
            <Button
              onClick={handleSetup}
              disabled={isSettingUp}
              className="w-full"
            >
              {isSettingUp ? (
                <Loader2 className="mr-2 size-4 animate-spin" />
              ) : (
                <Database className="mr-2 size-4" />
              )}
              Initialize Catalog Schema
            </Button>
          </CardContent>
        </Card>
      </div>
    )
  }

  // — Main catalog view —
  return (
    <div className="space-y-4 mt-4">
      {/* Demo banner */}
      {isDemoMode && (
        <div className="flex items-center gap-2 px-3 py-2 rounded-md bg-amber-50 dark:bg-amber-950/30 border border-amber-200 dark:border-amber-800 text-xs text-amber-800 dark:text-amber-300">
          <AlertCircle className="size-3.5 shrink-0" />
          Demo Mode — sample catalog data. Connect to a real project to profile your own tables and generate AI descriptions.
        </div>
      )}

      {/* Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
        <div className="flex items-center gap-3">
          <div className="p-1.5 rounded-lg bg-primary/10">
            <BookOpen className="size-4 text-primary" />
          </div>
          <div>
            <h2 className="font-semibold text-base">Data Catalog</h2>
            <p className="text-xs text-muted-foreground">
              {tables.length} tables · {profiledCount} profiled · {aiCount} with AI descriptions
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          {!isDemoMode && (
            <Button
              variant="outline"
              size="sm"
              onClick={loadCatalog}
              disabled={isLoading}
              className="gap-1.5"
            >
              <RefreshCw className={`size-3.5 ${isLoading ? 'animate-spin' : ''}`} />
              Refresh
            </Button>
          )}
          <Button
            variant="outline"
            size="sm"
            onClick={isDemoMode ? () => toast.info('Connect to a real project to profile tables') : handleProfileAll}
            disabled={isProfilingAll}
            className="gap-1.5"
          >
            {isProfilingAll ? (
              <Loader2 className="size-3.5 animate-spin" />
            ) : (
              <RotateCcw className="size-3.5" />
            )}
            Profile All
          </Button>
          <Button
            size="sm"
            onClick={isDemoMode ? () => toast.info('Connect to a real project to generate AI descriptions') : handleGenerateAll}
            disabled={isGeneratingAll || (!isDemoMode && profiledCount === 0)}
            className="gap-1.5"
          >
            {isGeneratingAll ? (
              <Loader2 className="size-3.5 animate-spin" />
            ) : (
              <Sparkles className="size-3.5" />
            )}
            Generate All AI
          </Button>
        </div>
      </div>

      {/* Stats bar */}
      <div className="flex items-center gap-4 text-xs text-muted-foreground border-b pb-2">
        <span className="flex items-center gap-1.5"><Database className="size-3" /><strong className="text-foreground">{tables.length}</strong> tables</span>
        <span className="flex items-center gap-1.5"><CheckCircle2 className="size-3 text-emerald-500" /><strong className="text-foreground">{profiledCount}</strong> profiled</span>
        <span className="flex items-center gap-1.5"><Sparkles className="size-3" /><strong className="text-foreground">{aiCount}</strong> with AI</span>
      </div>

      {/* Search + filter bar */}
      <div className="flex flex-col sm:flex-row gap-2">
        <div className="relative flex-1">
          <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 size-3.5 text-muted-foreground" />
          <Input
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search tables, columns, descriptions..."
            className="pl-8 h-8 text-sm"
          />
        </div>
        <Select value={schemaFilter} onValueChange={setSchemaFilter}>
          <SelectTrigger className="w-[140px] h-8 text-sm">
            <Filter className="size-3.5 mr-1.5 text-muted-foreground" />
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All schemas</SelectItem>
            {schemas.map((s) => (
              <SelectItem key={s} value={s}>{s}</SelectItem>
            ))}
          </SelectContent>
        </Select>
        <Select value={sortKey} onValueChange={(v) => setSortKey(v as SortKey)}>
          <SelectTrigger className="w-[140px] h-8 text-sm">
            <ArrowUpDown className="size-3.5 mr-1.5 text-muted-foreground" />
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="name">Sort: Name</SelectItem>
            <SelectItem value="row_count">Sort: Row count</SelectItem>
            <SelectItem value="profiled_at">Sort: Last profiled</SelectItem>
          </SelectContent>
        </Select>
      </div>

      {/* Table cards */}
      {filteredTables.length === 0 ? (
        <Card>
          <CardContent className="py-12 flex flex-col items-center justify-center text-center gap-3">
            <BookOpen className="size-8 text-muted-foreground/40" />
            {tables.length === 0 ? (
              <>
                <p className="font-medium">No tables cataloged yet</p>
                <p className="text-sm text-muted-foreground">Click "Profile All" to scan your database.</p>
              </>
            ) : (
              <>
                <p className="font-medium">No tables match your search</p>
                <p className="text-sm text-muted-foreground">Try a different search term or clear the filter.</p>
              </>
            )}
          </CardContent>
        </Card>
      ) : (
        <ScrollArea className="h-[calc(100vh-340px)]">
          <div className="space-y-2 pr-1">
            {filteredTables.map((table) => (
              <TableCard
                key={table.id}
                table={table}
                onReProfile={isDemoMode ? (_t: string) => toast.info('Connect to a real project to re-profile') : handleReProfile}
                onGenerateAI={isDemoMode ? (_t: CatalogTable) => toast.info('Connect to a real project to generate AI descriptions') : handleGenerateAI}
                onCommit={isDemoMode ? (_t: CatalogTable) => toast.info('Connect to a real project to commit descriptions') : handleCommit}
                isReprofiling={reprofilingTable === table.table_name}
                isGenerating={generatingTable === table.table_name || isGeneratingAll}
                isCommitting={committingTable === table.table_name}
              />
            ))}
          </div>
        </ScrollArea>
      )}
    </div>
  )
}
